### ISSUE TITLE
zero + challenge

### ISSUE THREAD

**Issue by westwq** [MAD11877/mad22-practical-3---event-handling-itsernestt#2]
https://github.com/MAD11877/mad22-practical-3---event-handling-itsernestt/blob/197555143744b7ffe9720e5754f7b127eba59ccf/app/src/main/java/sg/edu/np/mad/week2madprac/ListActivity.java#L25-L26
you dont hav to add zero, it doesnt have any effect

and your challenge question is missing

**Comment by itsernestt** [comment]
fixed errors and added challenge question
